require './tests/robot_test'
require './tests/position_test'
require './tests/sequence_translator_test'
require './tests/world_test'
require './tests/walls_test'
require './tests/round_test'
require './tests/printer_test'
